name: linkschool
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  curved_nav_bar: ^0.0.2
  flutter_rating_bar: ^4.0.1
  carousel_slider: ^5.1.1
  flip_card: ^0.7.0
  percent_indicator: ^4.0.1
  fl_chart: ^0.70.1
  intl: ^0.20.1
  image_picker: ^1.1.2
  file_picker: ^8.1.7
  shared_preferences: ^2.3.5
  introduction_screen: ^3.1.14
  flutter_plugin_android_lifecycle: ^2.0.24
  smooth_page_indicator: ^1.2.0+3
  dropdown_flutter: 1.0.1
  flutter_chat_types: ^3.4.3
  flutter_chat_ui: ^1.6.4
  uuid: ^3.0.6
  timezone: ^0.9.2
  jiffy: ^6.3.2
  skeletonizer: ^1.4.3
  
  # shimmer: ^3.0.0

 


  # xml: ^6.4.0
  # shimmer: ^3.0.0
  # shared_preferences: ^2.3.2
  # flutter_charts: ^0.5.2



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  # charts_flutter: ^0.12.0
  community_charts_flutter: ^1.0.0
  provider: ^6.1.2
  foundation: ^0.0.5
  chewie: ^1.10.0
  video_player: ^2.9.2
  bottom_picker: ^2.11.0
  flutter_dotenv: ^5.2.1
  fluttertoast: ^8.2.12
  url_launcher: ^6.3.1
  motion_toast: ^2.11.0
  share_plus: ^10.1.4
  sqflite: ^2.4.1
  path: ^1.9.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  get_it: ^8.0.3
  dio: ^5.8.0+1


  animated_custom_dropdown: ^3.1.1
  flutter_swiper_view: ^1.1.8
  freezed_annotation: ^2.4.1
  path_provider: ^2.1.5
  flutter_pdfview: ^1.4.1+1
  
  
 

  # freezed_annotation: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  freezed: ^2.4.1
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.5
  build_runner: ^2.4.15


flutter:


  uses-material-design: true


  assets:
    - .env
    - assets/icons/
    - assets/images/
    - assets/icons/e_learning/
    - assets/icons/result/
    - assets/icons/student/
    - assets/images/student/
    - assets/icons/profile/
    - assets/icons/staff/
    - assets/images/e-learning/
    - assets/images/result/
    - assets/images/admission/
    - assets/images/explore-images/
    - assets/images/profile/
    - assets/images/onboardng-image/
    - assets/images/gameDes/
    - assets/icons/gamesicon/
    - assets/images/video_images/
    - assets/images/e-subject_detail/
    - assets/images/news-images/
    - assets/icons/exams/
    # - assets/icons/home.svg
    # - assets/icons/e-learning.svg
    # - assets/icons/admission.svg
    # - assets/icons/games.svg
    # - assets/icons/cbt.svg


  fonts:
     - family: Urbanist
       fonts:
         - asset: assets/fonts/urbanist/Urbanist-Regular.ttf
           weight: 400
         - asset: assets/fonts/urbanist/Urbanist-Medium.ttf
           weight: 500
         - asset: assets/fonts/urbanist/Urbanist-MediumItalic.ttf
           weight: 500
           style: italic
         - asset: assets/fonts/urbanist/Urbanist-SemiBold.ttf
           weight: 600
         - asset: assets/fonts/urbanist/Urbanist-BoldItalic.ttf
           weight: 700