name: linkschool
description: "School Management System"

publish_to: 'none' 

version: 1.4.0+33

environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies: 
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  curved_nav_bar: ^0.0.2 
  flutter_rating_bar: ^4.0.1
  carousel_slider: ^5.1.1
  flip_card: ^0.7.0
  flutter_secure_storage: ^9.0.0
  percent_indicator: ^4.0.1
  intl: ^0.20.1
  image_picker: ^1.2.1
  file_picker: ^10.3.3
  shared_preferences: ^2.3.5
  introduction_screen: ^3.1.14
  flutter_plugin_android_lifecycle: ^2.0.24
  smooth_page_indicator: ^1.2.0+3
  dropdown_flutter: 1.0.1
  youtube_player_flutter: ^9.0.3
  flutter_chat_types: ^3.4.3
  flutter_chat_ui: ^1.6.4
  uuid: ^4.5.1
  timezone: ^0.9.2
  jiffy: ^6.3.2
  skeletonizer: ^2.1.2
  device_info_plus: ^10.1.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  community_charts_flutter: ^1.0.0
  provider: ^6.1.2
  foundation: ^0.0.5
  chewie: ^1.10.0
  video_player: ^2.9.2
  bottom_picker: ^2.11.0
  flutter_dotenv: ^5.2.1
  fluttertoast: ^8.2.12
  url_launcher: ^6.3.1
  fl_chart: ^0.69.0
  motion_toast: 2.11.0
  share_plus: ^10.1.4
  sqflite: ^2.4.1
  path: ^1.9.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  get_it: ^8.0.3
  dio: ^5.8.0+1
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  
  google_sign_in: ^6.2.1
  animated_custom_dropdown: ^3.1.1
  flutter_swiper_view: ^1.1.8
  freezed_annotation: ^2.4.1
  logger: ^2.6.0  
  webview_flutter: ^4.2.2
  webview_flutter_android: ^3.10.0
  dotted_line: ^3.2.3
  # open_file: ^3.5.10
  pdf: ^3.10.4
  printing: ^5.14.2
  permission_handler: ^11.3.0
  file_saver: ^0.2.14  
  path_provider: ^2.1.5
  flutter_pdfview: ^1.4.1+1
  cached_network_image: ^3.3.1
  pdfrx: ^1.0.0

  # pdfrx: ^1.3.5
  video_thumbnail: ^0.5.6
  # freezed_annotation: ^3.0.0
  flutter_charts: ^0.5.2
  open_filex: ^4.7.0
  paystack_for_flutter: ^1.0.0
  linkfy_text: ^1.1.6
  media_store_plus: ^0.1.3
  android_intent_plus: ^5.3.0
  
  http: any
  flutter_gif: ^0.0.4
  gif_view: ^1.0.3
  audioplayers: ^6.5.1
  vibration: ^3.1.4
  flutter_html: ^3.0.0
  markdown: ^7.3.0
  google_mobile_ads: ^5.2.0
  flutter_launcher_icons: ^0.14.4
  youtube_player_iframe: ^5.2.0
  awesome_notifications: 0.10.1
  firebase_messaging: ^15.2.10
  connectivity_plus: ^6.1.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  flutter_lints: ^5.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.11
dependency_overrides:

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/linkschool.jpeg"


flutter:
  uses-material-design: true

  assets:
    - assets/icons/invoice.png
    - assets/icons/naira.png
    # - .env
    - assets/icons/
    - assets/images/
    - assets/sounds/
    - assets/icons/e_learning/
    - assets/icons/result/
    - assets/icons/student/
    - assets/images/student/
    - assets/icons/profile/
    - assets/icons/staff/
    - assets/images/e-learning/
    - assets/images/result/
    - assets/images/admission/
    - assets/images/explore-images/
    - assets/images/profile/
    - assets/images/onboardng-image/
    - assets/images/gif/
    - assets/images/gameDes/
    - assets/icons/gamesicon/
    - assets/images/video_images/
    - assets/images/e-subject_detail/
    - assets/images/news-images/
    - assets/icons/exams/

  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/urbanist/Urbanist-Regular.ttf
          weight: 400
        - asset: assets/fonts/urbanist/Urbanist-Medium.ttf
          weight: 500
        - asset: assets/fonts/urbanist/Urbanist-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/urbanist/Urbanist-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/urbanist/Urbanist-BoldItalic.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 800
        # - asset: assets/fonts/Roboto-Regular.ttf
        # - asset: assets/fonts/Roboto-Bold.ttf
